### ISSUE TITLE
Please add keyup event

### ISSUE THREAD

**Issue by paulinetheitgirl** [GabiGrin/angular-validation-messages#7]
Please see sample at http://plnkr.co/edit/wXN7kBRlTWrA5ZDfG7Oc?p=preview
"ab" shows error message (correct)
"abc" hides error message (correct)
"abcd" hides error message (incorrect)

I've traced this and I think the cause is that the keydown event doesn't always get the last character typed. A keyup event would cover this case.

**Comment by GabiGrin** [comment]
thanks for the feedback! releasing now with this option
