### ISSUE TITLE
Use with input groups

### ISSUE THREAD

**Issue by sjorobekov** [GabiGrin/angular-validation-messages#9]
Is there any way to use it with
http://getbootstrap.com/components/#input-groups-checkboxes-radios

![580255f19d7fb3627f528b2ab52ba763](https://cloud.githubusercontent.com/assets/4434217/12776949/b97f58c8-ca94-11e5-87c9-cff51b9db471.png)

```
    <div class="input-group">
        <span class="input-group-addon">
          <input type="checkbox" ng-model="delivery.isInsuranceCovered"> Yes
        </span>
        <input id="insuranceCovered" 
               name="insuranceCovered" 
               ng-required="delivery.isInsuranceCovered"
               type="text" class="form-control"
               ng-model="delivery.insuranceCovered"
               ng-disabled="!delivery.isInsuranceCovered"
               maxlength="100" vmsg>
      </div>
```

**Comment by GabiGrin** [comment]
As currently it's not possible to defined a different container for the message (you are welcome to try doing it yourself and send a PR!), you can use css for that.
For example, you can make the validation message class `position: absolute` and make the input group container position relative.
See this plunker -> https://plnkr.co/edit/VEmuD8p1yvgo9gVuUkOO
